spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment-service
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
      cache: false

PSP:
  toss:
    secretKey: ${TOSS_SECRET_KEY:}
    url: https://api/tosspayments.com
