spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment_service
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
      cache: false

PSP:
  toss:
    secretKey: ${TOSS_SECRET_KEY:test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6}
    url: ${TOSS_API_URL:https://api.tosspayments.com}
